### ISSUE TITLE
Debug Warning

### ISSUE THREAD

**Issue by mungle** [rserro/pet#1]
Hello.... I think your script is great. I was testing it but when I press the "create" button the debug page display me these Warnings:

Warning: Model\Hash::create(): Property access is not allowed yet in /home2/myserver/public_html/mywebsite.org/tracking/model/Hash.php on line 53

Warning: Cannot modify header information - headers already sent by (output started at /home2/myserver/public_html/mywebsite.org/tracking/model/Hash.php:53) in /home2/myserver/public_html/mywebsite.org/tracking/lib/Controller.php on line 46

Should they have to be solved?
Thank you!

**Comment by ricardoserro** [comment]
Hi mungle! Sorry for the late response. Thanks for your feedback. 
I have checked and the warning was probably being rised because the statement was closed before accessing the affected_rows number. I`ve just pushed a commit fixing it. Please, let me know if the warning persists.
